# Generated by Django 4.1.3 on 2022-12-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='times',
        ),
        migrations.AddField(
            model_name='train',
            name='Destination',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='train',
            name='Source',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.DeleteModel(
            name='Timing',
        ),
    ]
