# Generated by Django 4.1.3 on 2023-01-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='cld',
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_no',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
