# Generated by Django 4.1.3 on 2023-02-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0002_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
