# Generated by Django 4.1.3 on 2022-12-27 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0002_remove_train_times_train_destination_train_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.IntegerField()),
                ('cls', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('nos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpro.seat_id')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpro.personal')),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpro.train')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=50)),
                ('cancel', models.CharField(max_length=50)),
                ('nos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpro.seat_id')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpro.personal')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpro.reservation')),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpro.train')),
            ],
        ),
    ]
