# Generated by Django 4.1.3 on 2023-01-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=30)),
                ('stock_sname', models.CharField(max_length=10)),
                ('sector_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Promotor_holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarterly', models.CharField(max_length=25)),
                ('promotor', models.IntegerField(default=0)),
                ('fii', models.IntegerField(default=0)),
                ('dii', models.IntegerField(default=0)),
                ('government', models.IntegerField(default=0)),
                ('public', models.IntegerField(default=0)),
                ('promotor_holding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockValues.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_cap', models.CharField(max_length=30)),
                ('curr_value', models.IntegerField(default=0)),
                ('face_value', models.IntegerField(default=0)),
                ('book_value', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockValues.stock')),
            ],
        ),
        migrations.CreateModel(
            name='PNL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quaterly', models.CharField(max_length=25)),
                ('sales', models.IntegerField(default=0)),
                ('expense', models.IntegerField(default=0)),
                ('other_income', models.IntegerField(default=0)),
                ('interest', models.IntegerField(default=0)),
                ('deprication', models.IntegerField(default=0)),
                ('profit_before_tax', models.IntegerField(default=0)),
                ('tax_percent', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockValues.stock')),
            ],
        ),
    ]
