# Generated by Django 4.1.3 on 2023-01-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockValues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnl',
            name='deprication',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pnl',
            name='expense',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pnl',
            name='interest',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pnl',
            name='other_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pnl',
            name='profit_before_tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pnl',
            name='sales',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pnl',
            name='tax_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='price',
            name='book_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='price',
            name='curr_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='price',
            name='face_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='promotor_holding',
            name='dii',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='promotor_holding',
            name='fii',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='promotor_holding',
            name='government',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='promotor_holding',
            name='promotor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='promotor_holding',
            name='public',
            field=models.FloatField(default=0.0),
        ),
    ]
