# Generated by Django 4.1.3 on 2023-01-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockValues', '0003_price_dividend_price_high_price_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='about',
            field=models.CharField(default='nothing', max_length=1024),
        ),
    ]
