# Generated by Django 4.1.3 on 2023-01-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(default=None, max_length=200)),
                ('dept', models.CharField(default=None, max_length=200)),
                ('dateofjoing', models.DateField()),
                ('photofilename', models.CharField(max_length=50)),
            ],
        ),
    ]
